added deployment to Cloudflare Pages

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -203,3 +203,26 @@ jobs:
         uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f #v4.8.0
         with:
           folder: ${{ env.BUILD_ARTIFACT_FOLDER }}
+
+  # Deploy to Cloudflare Pages
+  deploy-cf-pages:
+    needs:
+      - static-analysis
+      - build
+      - test
+      - e2e
+    runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/main'
+    concurrency:
+      group: deploy_cf_pages
+    env:
+      HOOK_ID: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK_ID }}
+    steps:
+      - name: Trigger deployment to Cloudflare Pages
+        run: |
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -d "" "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${HOOK_ID}")
+          echo "HTTP response status: $STATUS"
+          if [ "$STATUS" -ne 200 ]; then
+            echo "Deployment trigger failed!"
+            exit 1
+          fi
